spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  output:
    ansi:
      enabled: always
  cloud:
    compatibility-verifier:
      enabled: false
    openfeign:
      autoconfiguration:
        jackson:
          enabled: false
  datasource:
    url: ${PROD_SQLITE_DB_URL:jdbc:sqlite:./ranp.db}
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    show-sql: false
  h2:
    console:
      enabled: false
  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: classpath:/db/changelog/db.changelog-master.xml
content:
  service:
    url: ${ALFRESCO_BASE_PATH:http://localhost:8080}
    security:
      basicAuth:
        username: ${ALFRESCO_USERNAME:admin}
        password: ${ALFRESCO_PASSWORD:admin}
application:
  queue-size: ${QUEUE_SIZE:1000}
  consumer-threads: ${CONSUMER_THREADS:4}
  consumer-timeout: ${CONSUMER_TIMEOUT:5000}
  rate-limit-ms: ${RATE_LIMIT_MS:0}
  processor-retry-delay-seconds: ${PROCESSOR_RETRY_DELAY_SECONDS:0}
  processor-max-retry-count: ${PROCESSOR_MAX_RETRY_COUNT:5}
  read-only: ${READ_ONLY:true}
  stats-service:
    enabled: true
    print-interval: 5